# Generated by Django 5.1.4 on 2024-12-23 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='new list', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('private', 'Private (Only Me)'), ('public', 'Public (My Friends)')], default='private', max_length=10)),
                ('category', models.CharField(choices=[('hobby', 'Hobby'), ('gifts', 'Gifts'), ('home-decor', 'Home Decor'), ('books', 'Books'), ('health', 'Health'), ('electronics', 'Electronics'), ('clothing&accesories', 'Clothing & Accessories'), ('kitchen', 'Kitchen'), ('beauty', 'Beauty'), ('stationery', 'Stationery'), ('sports', 'Sports'), ('travel', 'Travel'), ('tech', 'Tech'), ('finance', 'Finance'), ('education', 'Education'), ('events', 'Events'), ('charity', 'Charity'), ('services', 'Services'), ('other', 'Other')], default='other', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_set', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price_range', models.CharField(choices=[('0_100', '0 to 100'), ('101_200', '101 to 200'), ('201_300', '201 to 300'), ('301_500', '301 to 500'), ('501_1000', '501 to 1000'), ('1001_2000', '1001 to 2000'), ('2001_5000', '2001 to 5000'), ('5001_above', '5001 and above')], max_length=10)),
                ('url', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='wishlist_items/')),
                ('bought', models.BooleanField(default=False)),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wishlists.wishlist')),
            ],
        ),
    ]
